version: '3.8'

services:
  bot:
    container_name: bot
    build: .
  db:
    container_name: db
    ports:
      - '1234:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:14.5